"""core schema contracts."""

# ruff: noqa: E501

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2b24c7780727"
down_revision: str | None = "0001_runtime_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("subject_type", sa.String(length=120), nullable=False),
        sa.Column("subject_id", sa.String(length=160), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("target", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending', 'sent', 'failed')", name="ck_outbox_events_status"
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name="ck_outbox_events_retry_nonnegative"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_events_idempotency"),
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_repo_id", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("default_branch", sa.String(length=120), nullable=False),
        sa.Column("sync_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("provider in ('github')", name="ck_repositories_provider"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_repo_id", name="uq_repositories_provider_id"
        ),
    )
    op.create_table(
        "scheduler_cycles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("queue_key", sa.String(length=160), nullable=False),
        sa.Column("input_version", sa.String(length=160), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("assigned_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduler_guards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("queue_key", sa.String(length=160), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("queue_key", name="uq_scheduler_guards_queue"),
    )
    op.create_table(
        "work_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("work_type", sa.String(length=32), nullable=False),
        sa.Column("autonomy_mode", sa.String(length=32), nullable=False),
        sa.Column("acceptance", sa.Text(), nullable=True),
        sa.Column("validation", sa.Text(), nullable=True),
        sa.Column("expected_touch", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "autonomy_mode in ('human_required', 'ai_assisted', 'fully_autonomous')",
            name="ck_work_items_autonomy",
        ),
        sa.CheckConstraint(
            "risk in ('low', 'medium', 'high', 'critical')", name="ck_work_items_risk"
        ),
        sa.CheckConstraint(
            "status in ('needs_triage', 'backlog', 'ready', 'claimed', 'implementing', 'pr_open', 'waiting_checks', 'merge_armed', 'merged', 'done', 'blocked', 'human_decision', 'strict_ai_review', 'ci_failed', 'gate_failed')",
            name="ck_work_items_status",
        ),
        sa.CheckConstraint(
            "work_type in ('implementation', 'docs', 'test', 'design', 'governance', 'operations')",
            name="ck_work_items_type",
        ),
        sa.CheckConstraint("priority >= 0", name="ck_work_items_priority_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "external_refs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_type", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("work_item_id", sa.String(length=36), nullable=True),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("provider in ('github')", name="ck_external_refs_provider"),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "external_type",
            "external_id",
            name="uq_external_refs_provider_type_id",
        ),
    )
    op.create_table(
        "inbound_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=True),
        sa.Column("external_id", sa.String(length=240), nullable=True),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("provider in ('github')", name="ck_inbound_events_provider"),
        sa.CheckConstraint(
            "status in ('pending', 'processed', 'failed', 'skipped')",
            name="ck_inbound_events_status",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "idempotency_key", name="uq_inbound_events_idempotency"
        ),
    )
    op.create_table(
        "leases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("fencing_token", sa.String(length=120), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('active', 'expired', 'released', 'superseded')",
            name="ck_leases_status",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fencing_token", name="uq_leases_fencing_token"),
    )
    op.create_index(
        "uq_leases_active_work_item",
        "leases",
        ["work_item_id"],
        unique=True,
        sqlite_where=sa.text("status = 'active'"),
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "repo_pull_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=True),
        sa.Column("provider_pr_id", sa.String(length=160), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("draft", sa.Boolean(), nullable=False),
        sa.Column("head_branch", sa.String(length=240), nullable=True),
        sa.Column("head_sha", sa.String(length=80), nullable=True),
        sa.Column("merged", sa.Boolean(), nullable=False),
        sa.Column("merge_commit_sha", sa.String(length=80), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state in ('open', 'closed', 'merged')", name="ck_repo_pr_state"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_id", "provider_pr_id", name="uq_repo_pull_requests_provider_pr"
        ),
    )
    op.create_table(
        "scheduler_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cycle_id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("blocking_facts", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code in ('assigned', 'blocked_by_dependency', 'blocked_by_status', 'blocked_by_conflict_key', 'blocked_by_capacity', 'blocked_by_missing_expected_touch', 'blocked_by_missing_acceptance', 'blocked_by_missing_validation', 'blocked_by_review_gate', 'blocked_by_ci', 'blocked_by_human_decision', 'blocked_by_expired_or_stale_source')",
            name="ck_scheduler_decisions_code",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["scheduler_cycles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_cursors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("sync_kind", sa.String(length=80), nullable=False),
        sa.Column("cursor", sa.String(length=500), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("provider in ('github')", name="ck_sync_cursors_provider"),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "repository_id", "sync_kind", name="uq_sync_cursors_scope"
        ),
    )
    op.create_table(
        "work_item_conflict_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("conflict_key", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"], ["work_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "work_item_id", "conflict_key", name="uq_work_item_conflict_keys_item_key"
        ),
    )
    op.create_table(
        "work_item_dependencies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("depends_on_work_item_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "work_item_id <> depends_on_work_item_id",
            name="ck_work_item_dependencies_no_self",
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_work_item_id"], ["work_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"], ["work_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "work_item_id",
            "depends_on_work_item_id",
            name="uq_work_item_dependencies_edge",
        ),
    )
    op.create_table(
        "lock_holders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conflict_key", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("lease_id", sa.String(length=36), nullable=True),
        sa.Column("pull_request_id", sa.String(length=36), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source in ('lease', 'pull_request', 'fallback')",
            name="ck_lock_holders_source",
        ),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["leases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["repo_pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_lock_holders_active_key",
        "lock_holders",
        ["conflict_key"],
        unique=True,
        sqlite_where=sa.text("released_at IS NULL"),
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "repo_check_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pull_request_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("conclusion", sa.String(length=32), nullable=False),
        sa.Column("head_sha", sa.String(length=80), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("details_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "conclusion in ('success', 'failure', 'cancelled', 'skipped', 'timed_out', 'action_required', 'neutral', 'unknown')",
            name="ck_repo_checks_conclusion",
        ),
        sa.CheckConstraint(
            "status in ('queued', 'in_progress', 'completed', 'unknown')",
            name="ck_repo_checks_status",
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["repo_pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pull_request_id",
            "name",
            "head_sha",
            name="uq_repo_check_summaries_pr_name_head",
        ),
    )
    op.create_table(
        "repo_review_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pull_request_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("unresolved_count", sa.Integer(), nullable=False),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state in ('unknown', 'waiting', 'approved', 'changes_requested', 'unresolved_threads')",
            name="ck_repo_review_summaries_state",
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["repo_pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pull_request_id", name="uq_repo_review_summaries_pr"),
    )
    op.create_table(
        "worker_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("lease_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=True),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("public_mutations", sa.JSON(), nullable=False),
        sa.Column("cost_summary", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result is null or result in ('done', 'blocked', 'failed', 'superseded', 'abandoned')",
            name="ck_worker_runs_result",
        ),
        sa.CheckConstraint(
            "role in ('worker', 'reviewer', 'scheduler', 'triager', 'repair_agent', 'consultant')",
            name="ck_worker_runs_role",
        ),
        sa.CheckConstraint(
            "status in ('planned', 'claimed', 'running', 'reporting', 'closed')",
            name="ck_worker_runs_status",
        ),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["leases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worker_runs")
    op.drop_table("repo_review_summaries")
    op.drop_table("repo_check_summaries")
    op.drop_index(
        "uq_lock_holders_active_key",
        table_name="lock_holders",
        sqlite_where=sa.text("released_at IS NULL"),
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("lock_holders")
    op.drop_table("work_item_dependencies")
    op.drop_table("work_item_conflict_keys")
    op.drop_table("sync_cursors")
    op.drop_table("scheduler_decisions")
    op.drop_table("repo_pull_requests")
    op.drop_index(
        "uq_leases_active_work_item",
        table_name="leases",
        sqlite_where=sa.text("status = 'active'"),
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("leases")
    op.drop_table("inbound_events")
    op.drop_table("external_refs")
    op.drop_table("work_items")
    op.drop_table("scheduler_guards")
    op.drop_table("scheduler_cycles")
    op.drop_table("repositories")
    op.drop_table("outbox_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
